spin_manifest_version = 2

[application]
authors = ["Karthik Ganeshram <karthik.ganeshram@fermyon.com>"]
description = ""
name = "kv-sample"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "kv-sample"

[component.kv-sample]
source = "dist/kv-sample.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
[component.kv-sample.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]

[[trigger.http]]
component = "kv-explorer"
route = "/internal/kv-explorer/..."

[component.kv-explorer]
source = "modules/fwf-kv-explorer.wasm"
allowed_outbound_hosts = ["https://*.fermyon.tech"]
# "default" is the only KV store available for Fermyon Wasm Functions
key_value_stores = ["default"]
