spin_manifest_version = 2

[application]
name = "wizened-sample"
version = "0.1.0"
authors = ["Karthik Ganeshram <karthik.ganeshram@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "wizened-sample"

[component.wizened-sample]
source = "wizened_sample.wasm"
allowed_outbound_hosts = []
[component.wizened-sample.build]
command = "./build.sh wizened_sample.wasm"
watch = ["src/**/*.rs", "Cargo.toml"]
